run:
  timeout: 2m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - funlen
    - gocyclo
    - gofmt
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused

linters-settings:
  funlen:
    lines: 70
    statements: 45
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 100
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: duplicated-imports
      - name: early-return
      - name: error-naming
      - name: error-return
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: unreachable-code
      - name: unused-parameter

issues:
  exclude-dirs:
    - .direnv
