package ast

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/kizu-lang/kizu/internal/typ"
)

// Position identifies a source position using one-based line and column values.
type Position struct {
	Line   int
	Column int
}

// Span identifies a half-open source range using one-based positions.
//
// File is the path the range was read from. A package is checked as one merged
// program, so without it a diagnostic's line and column say nothing about which
// module they belong to.
type Span struct {
	File  string
	Start Position
	End   Position
}

// IsZero reports whether a span has no source position.
func (s Span) IsZero() bool {
	return s.Start.Line == 0 || s.Start.Column == 0
}

// Node is implemented by every AST node.
type Node interface {
	String() string
}

// Statement is implemented by nodes that can appear as statements.
type Statement interface {
	Node
	statementNode()
}

// Expression is implemented by nodes that produce a value.
type Expression interface {
	Node
	expressionNode()
}

// Program is the root AST node for a Kizu source file.
type Program struct {
	Decls []Decl
}

// ImportDecl represents one explicit top-level module import.
type ImportDecl struct {
	Path []string
}

// declNode marks ImportDecl as a declaration node.
func (*ImportDecl) declNode() {}

// String returns a compact debug representation of the import declaration.
func (d *ImportDecl) String() string {
	return "import " + strings.Join(d.Path, "::")
}

// Decl is implemented by top-level declarations.
type Decl interface {
	Node
	declNode()
}

// String returns a compact debug representation of the program.
func (p *Program) String() string {
	var out bytes.Buffer
	for i, decl := range p.Decls {
		if i > 0 {
			out.WriteByte('\n')
		}
		out.WriteString(decl.String())
	}
	return out.String()
}

// FunctionSignature is everything a caller is promised: the declaration without
// its body or its doc comment.
//
// It is a type of its own so that the code deciding what a call site sees
// cannot reach the body. A signature that came from a body is a signature no
// other package can be told without being shipped the body, and the shape of
// the compiler follows from that: a package is described to another package by
// this, and only generic and comptime bodies travel with it because
// instantiation reruns them.
type FunctionSignature struct {
	// Receiver reports whether Params[0] is the value this function is a method
	// on. A method is filed under its receiver's type rather than in its module,
	// so two types in one module may each have a `len`.
	Receiver bool
	Name     string
	// StaticParams is the `<...>` list. An entry with no declared type is a
	// type parameter; one with a type is a compile-time value. Both are
	// compile-time, which is why they live here and not in Params.
	StaticParams   []StaticParam
	Params         []Param
	ReturnType     typ.Type
	ReturnBorrow   string
	RequiresUnsafe bool
	ExternABI      string
	Public         bool
	Std            bool
}

// FunctionDecl represents a function declaration.
type FunctionDecl struct {
	FunctionSignature
	Doc  string
	Body *BlockStmt
	// FieldsBody marks a `deinit() -> void = fields;` declaration whose body is
	// generated by ExpandFieldsDeinit before any checker reads it (ADR-0091).
	FieldsBody bool
}

// StaticParam is one entry of a `<...>` static argument list.
type StaticParam struct {
	Name string
	// Type is absent for a type parameter, and names the value's type for a
	// compile-time value such as `<n: i64>` or `<worker: Function>`.
	Type typ.Type
}

// IsType reports whether this entry declares a type parameter.
func (p StaticParam) IsType() bool { return p.Type == nil }

// String renders the parameter as it is written in source.
func (p StaticParam) String() string {
	if p.IsType() {
		return p.Name
	}
	return p.Name + ": " + p.Type.String()
}

// TypeParamNames returns the names of the entries that declare types.
func (s *FunctionSignature) TypeParamNames() []string {
	names := []string{}
	for _, param := range s.StaticParams {
		if param.IsType() {
			names = append(names, param.Name)
		}
	}
	return names
}

// declNode marks FunctionDecl as a declaration node.
func (*FunctionDecl) declNode() {}

// String returns a compact debug representation of the function.
func (d *FunctionDecl) String() string {
	receiver := ""
	rest := d.Params
	if d.Receiver && len(rest) > 0 {
		receiver = "(" + rest[0].String() + ") "
		rest = rest[1:]
	}
	params := make([]string, 0, len(rest))
	for _, p := range rest {
		params = append(params, p.String())
	}
	ret := ""
	if d.ReturnType != nil {
		ret = " -> " + d.ReturnType.String()
		if d.ReturnBorrow != "" {
			ret += " borrows " + d.ReturnBorrow
		}
	}
	typeParams := staticParamText(d.StaticParams)
	if typeParams != "" {
		typeParams = "<" + typeParams + ">"
	}
	prefix := ""
	if d.Public {
		prefix += "pub "
	}
	if d.RequiresUnsafe {
		prefix += "unsafe "
	}
	if d.ExternABI != "" {
		return fmt.Sprintf("%sextern %q fn %s%s%s(%s)%s",
			prefix, d.ExternABI, receiver, d.Name, typeParams, strings.Join(params, ", "), ret)
	}
	if d.Body == nil {
		return fmt.Sprintf("%sfn %s%s%s(%s)%s;",
			prefix, receiver, d.Name, typeParams, strings.Join(params, ", "), ret)
	}
	return fmt.Sprintf("%sfn %s%s%s(%s)%s %s",
		prefix, receiver, d.Name, typeParams, strings.Join(params, ", "), ret, d.Body.String())
}

// TestDecl represents a top-level test block.
type TestDecl struct {
	Name string
	Body *BlockStmt
}

// declNode marks TestDecl as a declaration node.
func (*TestDecl) declNode() {}

// String returns a compact debug representation of the test declaration.
func (d *TestDecl) String() string {
	if d.Body == nil {
		return fmt.Sprintf("test %q <missing>", d.Name)
	}
	return fmt.Sprintf("test %q %s", d.Name, d.Body.String())
}

// StructDecl represents a top-level struct declaration.
type StructDecl struct {
	Name       string
	Doc        string
	TypeParams []string
	Fields     []Field
	Public     bool
	// RequiresUnsafe marks a struct whose fields carry an invariant the
	// compiler cannot check, spelled `unsafe struct`. Establishing or changing
	// that invariant is what needs `unsafe`, so writes are marked and reads are
	// not.
	RequiresUnsafe bool
}

// declNode marks StructDecl as a declaration node.
func (*StructDecl) declNode() {}

// String returns a compact debug representation of the struct declaration.
func (d *StructDecl) String() string {
	fields := make([]string, 0, len(d.Fields))
	for _, field := range d.Fields {
		fields = append(fields, field.String())
	}
	prefix := ""
	if d.Public {
		prefix = "pub "
	}
	if d.RequiresUnsafe {
		prefix += "unsafe "
	}
	typeParams := typeParamText(d.TypeParams)
	if typeParams != "" {
		typeParams = "<" + typeParams + ">"
	}
	return fmt.Sprintf("%sstruct %s%s { %s }",
		prefix, d.Name, typeParams, strings.Join(fields, ", "))
}

// EnumDecl represents a Zig/C-style tag enum declaration.
type EnumDecl struct {
	Name    string
	Doc     string
	Tags    []string
	TagDocs map[string]string
	Public  bool
}

// declNode marks EnumDecl as a declaration node.
func (*EnumDecl) declNode() {}

// String returns a compact debug representation of the enum declaration.
func (d *EnumDecl) String() string {
	prefix := ""
	if d.Public {
		prefix = "pub "
	}
	return fmt.Sprintf("%senum %s { %s }", prefix, d.Name, strings.Join(d.Tags, ", "))
}

// ErrorSetDecl represents `error Name { A, B }`. An error set names the failures
// a function can return. Its members carry nothing: an error says what went
// wrong, and what else is worth knowing about it belongs to a diagnostic.
//
// It is not an enum. An enum is a closed set of values a program computes with,
// while an error set is a set that grows by union as callers propagate what
// they call, which is what lets `!T` be inferred from a function body.
type ErrorSetDecl struct {
	Name       string
	Doc        string
	Members    []string
	MemberDocs map[string]string
	Public     bool
}

// declNode marks ErrorSetDecl as a declaration node.
func (*ErrorSetDecl) declNode() {}

// String returns a compact debug representation of the error set declaration.
func (d *ErrorSetDecl) String() string {
	prefix := ""
	if d.Public {
		prefix = "pub "
	}
	return fmt.Sprintf("%serror %s { %s }", prefix, d.Name, strings.Join(d.Members, ", "))
}

// UnionDecl represents a tagged union declaration.
type UnionDecl struct {
	Name       string
	Doc        string
	TypeParams []string
	Variants   []UnionVariant
	Public     bool
}

// declNode marks UnionDecl as a declaration node.
func (*UnionDecl) declNode() {}

// String returns a compact debug representation of the union declaration.
func (d *UnionDecl) String() string {
	variants := make([]string, 0, len(d.Variants))
	for _, variant := range d.Variants {
		variants = append(variants, variant.String())
	}
	prefix := ""
	if d.Public {
		prefix = "pub "
	}
	typeParams := typeParamText(d.TypeParams)
	if typeParams != "" {
		typeParams = "<" + typeParams + ">"
	}
	return fmt.Sprintf("%sunion %s%s { %s }",
		prefix, d.Name, typeParams, strings.Join(variants, ", "))
}

// UnionVariant represents one tagged union variant.
type UnionVariant struct {
	Name    string
	Doc     string
	Payload typ.Type
}

// String returns a compact debug representation of the union variant.
func (v UnionVariant) String() string {
	if v.Payload == nil {
		return v.Name
	}
	return fmt.Sprintf("%s(%s)", v.Name, v.Payload)
}

// ContractDecl represents required method signatures.
type ContractDecl struct {
	Name    string
	Methods []*FunctionDecl
	Public  bool
}

// declNode marks ContractDecl as a declaration node.
func (*ContractDecl) declNode() {}

// String returns a compact debug representation of the contract declaration.
func (d *ContractDecl) String() string {
	methods := make([]string, 0, len(d.Methods))
	for _, method := range d.Methods {
		methods = append(methods, method.String())
	}
	prefix := ""
	if d.Public {
		prefix = "pub "
	}
	return fmt.Sprintf("%scontract %s { %s }", prefix, d.Name, strings.Join(methods, "; "))
}

// ImplDecl asserts that one concrete type satisfies one contract. A type
// satisfies a contract by having the methods, so this carries no body: it asks
// for the check to run where it is written.
type ImplDecl struct {
	ContractName string
	TypeName     string
}

// declNode marks ImplDecl as a declaration node.
func (*ImplDecl) declNode() {}

// String returns a compact debug representation of the impl declaration.
func (d *ImplDecl) String() string {
	return fmt.Sprintf("impl %s for %s;", d.ContractName, d.TypeName)
}

// Field represents a named struct field.
type Field struct {
	Name      string
	Doc       string
	TypeName  typ.Type
	Borrow    bool
	MutBorrow bool
	Public    bool
}

// String returns a compact debug representation of the field.
func (f Field) String() string {
	prefix := ""
	if f.MutBorrow {
		prefix = borrowPrefix(true)
	} else if f.Borrow {
		prefix = borrowPrefix(false)
	}
	visibility := ""
	if f.Public {
		visibility = "pub "
	}
	return fmt.Sprintf("%s%s: %s%s", visibility, f.Name, prefix, f.TypeName)
}

// Param represents a function parameter.
type Param struct {
	Name      string
	TypeName  typ.Type
	Borrow    bool
	MutBorrow bool
}

// String returns a compact debug representation of the parameter.
func (p Param) String() string {
	prefix := ""
	if p.MutBorrow {
		prefix = borrowPrefix(true)
	} else if p.Borrow {
		prefix = borrowPrefix(false)
	}
	return fmt.Sprintf("%s: %s%s", p.Name, prefix, p.TypeName)
}

// typeParamText renders static type parameters.
func typeParamText(types []string) string {
	return strings.Join(types, ", ")
}

// staticParamText renders a `<...>` declaration list.
func staticParamText(params []StaticParam) string {
	parts := make([]string, 0, len(params))
	for _, param := range params {
		parts = append(parts, param.String())
	}
	return strings.Join(parts, ", ")
}

// borrowPrefix renders a borrow marker.
func borrowPrefix(mutable bool) string {
	if mutable {
		return "&var "
	}
	return "&"
}

// BlockStmt represents a sequence of statements.
type BlockStmt struct {
	Statements []Statement
}

// statementNode marks BlockStmt as a statement node.
func (*BlockStmt) statementNode() {}

// String returns a compact debug representation of the block.
func (s *BlockStmt) String() string {
	parts := make([]string, 0, len(s.Statements))
	for _, stmt := range s.Statements {
		parts = append(parts, stmt.String())
	}
	return "{ " + strings.Join(parts, " ") + " }"
}

// LetStmt represents a let or var declaration.
type LetStmt struct {
	Mutable bool
	Name    string
	Value   Expression
}

// statementNode marks LetStmt as a statement node.
func (*LetStmt) statementNode() {}

// String returns a compact debug representation of the declaration.
func (s *LetStmt) String() string {
	kw := "let"
	if s.Mutable {
		kw = "var"
	}
	return fmt.Sprintf("%s %s = %s;", kw, s.Name, s.Value.String())
}

// AssignStmt represents assignment to an existing binding.
type AssignStmt struct {
	Target Expression
	Value  Expression
}

// statementNode marks AssignStmt as a statement node.
func (*AssignStmt) statementNode() {}

// String returns a compact debug representation of the assignment.
func (s *AssignStmt) String() string {
	return fmt.Sprintf("%s = %s;", s.Target.String(), s.Value.String())
}

// ReturnStmt represents an explicit return statement.
type ReturnStmt struct {
	Value Expression
}

// statementNode marks ReturnStmt as a statement node.
func (*ReturnStmt) statementNode() {}

// String returns a compact debug representation of the return statement.
func (s *ReturnStmt) String() string {
	if s.Value == nil {
		return "return;"
	}
	return "return " + s.Value.String() + ";"
}

// DeferStmt registers one cleanup expression for the current lexical block.
type DeferStmt struct {
	Expr Expression
}

// statementNode marks DeferStmt as a statement node.
func (*DeferStmt) statementNode() {}

// String returns a compact debug representation of the defer statement.
func (s *DeferStmt) String() string {
	return "defer " + s.Expr.String() + ";"
}

// ErrDeferStmt registers one cleanup expression that runs only when the current
// lexical block exits through an error-return path.
type ErrDeferStmt struct {
	Expr Expression
}

// statementNode marks ErrDeferStmt as a statement node.
func (*ErrDeferStmt) statementNode() {}

// String returns a compact debug representation of the errdefer statement.
func (s *ErrDeferStmt) String() string {
	return "errdefer " + s.Expr.String() + ";"
}

// IfStmt represents a conditional branch.
type IfStmt struct {
	Condition   Expression
	Consequence *BlockStmt
	Alternative *BlockStmt
}

// statementNode marks IfStmt as a statement node.
func (*IfStmt) statementNode() {}

// expressionNode marks IfStmt as an expression node.
func (*IfStmt) expressionNode() {}

// String returns a compact debug representation of the if statement.
func (s *IfStmt) String() string {
	out := fmt.Sprintf("if %s %s", s.Condition.String(), s.Consequence.String())
	if s.Alternative != nil {
		out += " else " + s.Alternative.String()
	}
	return out
}

// WhileStmt represents a loop guarded by a condition expression.
type WhileStmt struct {
	Label     string
	Condition Expression
	Body      *BlockStmt
}

// statementNode marks WhileStmt as a statement node.
func (*WhileStmt) statementNode() {}

// String returns a compact debug representation of the while statement.
func (s *WhileStmt) String() string {
	out := fmt.Sprintf("while %s %s", s.Condition.String(), s.Body.String())
	if s.Label != "" {
		return s.Label + ": " + out
	}
	return out
}

// ForStmt represents a bounded integer range loop.
type ForStmt struct {
	Label string
	Name  string
	Start Expression
	End   Expression
	Body  *BlockStmt
}

// statementNode marks ForStmt as a statement node.
func (*ForStmt) statementNode() {}

// String returns a compact debug representation of the for statement.
func (s *ForStmt) String() string {
	out := fmt.Sprintf("for %s..%s |%s| %s",
		s.Start.String(), s.End.String(), s.Name, s.Body.String())
	if s.Label != "" {
		return s.Label + ": " + out
	}
	return out
}

// BreakStmt exits the nearest loop or a named enclosing loop.
type BreakStmt struct {
	Label string
}

// statementNode marks BreakStmt as a statement node.
func (*BreakStmt) statementNode() {}

// String returns a compact debug representation of break.
func (s *BreakStmt) String() string {
	if s.Label != "" {
		return "break :" + s.Label + ";"
	}
	return "break;"
}

// ContinueStmt skips to the next iteration of the nearest or named loop.
type ContinueStmt struct {
	Label string
}

// statementNode marks ContinueStmt as a statement node.
func (*ContinueStmt) statementNode() {}

// String returns a compact debug representation of continue.
func (s *ContinueStmt) String() string {
	if s.Label != "" {
		return "continue :" + s.Label + ";"
	}
	return "continue;"
}

// MatchStmt represents a simple enum tag match statement.
type MatchStmt struct {
	Value Expression
	Arms  []MatchArm
}

// statementNode marks MatchStmt as a statement node.
func (*MatchStmt) statementNode() {}

// expressionNode marks MatchStmt as an expression node.
func (*MatchStmt) expressionNode() {}

// String returns a compact debug representation of the match statement.
func (s *MatchStmt) String() string {
	arms := make([]string, 0, len(s.Arms))
	for _, arm := range s.Arms {
		arms = append(arms, arm.String())
	}
	return fmt.Sprintf("match %s { %s }", s.Value.String(), strings.Join(arms, ", "))
}

// MatchArm represents one enum tag branch in a match statement.
type MatchArm struct {
	Tag     string
	Binding string
	Body    Statement
}

// IsWildcard reports whether the arm is the fallback match arm.
func (a MatchArm) IsWildcard() bool {
	return a.Tag == "_"
}

// String returns a compact debug representation of the match arm.
func (a MatchArm) String() string {
	body := a.Body.String()
	if expr, ok := a.Body.(*ExprStmt); ok && !expr.Semicolon {
		body = expr.Expr.String()
	}
	if a.Binding != "" {
		return fmt.Sprintf("%s(%s) => %s", a.Tag, a.Binding, body)
	}
	return fmt.Sprintf("%s => %s", a.Tag, body)
}

// ComptimeIfStmt represents a branch selected during compilation.
type ComptimeIfStmt struct {
	Condition   Expression
	Consequence *BlockStmt
	Alternative *BlockStmt
}

// statementNode marks ComptimeIfStmt as a statement node.
func (*ComptimeIfStmt) statementNode() {}

// String returns a compact debug representation of the comptime branch.
func (s *ComptimeIfStmt) String() string {
	out := fmt.Sprintf("comptime if %s %s", s.Condition.String(), s.Consequence.String())
	if s.Alternative != nil {
		out += " else " + s.Alternative.String()
	}
	return out
}

// ExprStmt wraps an expression used as a statement.
type ExprStmt struct {
	Expr      Expression
	Semicolon bool
}

// statementNode marks ExprStmt as a statement node.
func (*ExprStmt) statementNode() {}

// String returns a compact debug representation of the expression statement.
func (s *ExprStmt) String() string {
	return s.Expr.String() + ";"
}

// IdentExpr represents a name reference.
type IdentExpr struct {
	Name string
	Span Span
	// SlotDepth/SlotIndex are a lexical address precomputed by the interpreter
	// resolver, valid only when SlotResolved is true and the name is
	// unambiguous in scope. Evaluation verifies the binding name and falls
	// back to name lookup otherwise.
	SlotDepth    int
	SlotIndex    int
	SlotResolved bool
}

// expressionNode marks IdentExpr as an expression node.
func (*IdentExpr) expressionNode() {}

// String returns the identifier name.
func (e *IdentExpr) String() string {
	return e.Name
}

// IntExpr represents an integer literal.
type IntExpr struct {
	Value string
	// Parsed holds the decimal value precomputed at parse time; Parsed is
	// only valid when ParseOK is true. Evaluators fall back to reparsing
	// Value otherwise so overflow still surfaces at the original point.
	Parsed  int64
	ParseOK bool
}

// expressionNode marks IntExpr as an expression node.
func (*IntExpr) expressionNode() {}

// String returns the literal spelling.
func (e *IntExpr) String() string {
	return e.Value
}

// StringExpr represents a string literal.
type StringExpr struct {
	Value string
}

// expressionNode marks StringExpr as an expression node.
func (*StringExpr) expressionNode() {}

// String returns the quoted literal spelling.
func (e *StringExpr) String() string {
	return fmt.Sprintf("%q", e.Value)
}

// BoolExpr represents a boolean literal.
type BoolExpr struct {
	Value bool
}

// expressionNode marks BoolExpr as an expression node.
func (*BoolExpr) expressionNode() {}

// String returns the boolean literal spelling.
func (e *BoolExpr) String() string {
	if e.Value {
		return "true"
	}
	return "false"
}

// TypeExpr represents a compile-time type value.
type TypeExpr struct {
	TypeName string
}

// expressionNode marks TypeExpr as an expression node.
func (*TypeExpr) expressionNode() {}

// String returns the type literal spelling.
func (e *TypeExpr) String() string {
	return "type<" + e.TypeName + ">"
}

// ComptimeExpr represents an expression evaluated during compilation.
type ComptimeExpr struct {
	Expr Expression
}

// expressionNode marks ComptimeExpr as an expression node.
func (*ComptimeExpr) expressionNode() {}

// String returns a compact debug representation of the comptime expression.
func (e *ComptimeExpr) String() string {
	return "comptime " + e.Expr.String()
}

// PrefixExpr represents a unary operator expression.
type PrefixExpr struct {
	Operator string
	Right    Expression
}

// expressionNode marks PrefixExpr as an expression node.
func (*PrefixExpr) expressionNode() {}

// String returns a compact debug representation of the prefix expression.
func (e *PrefixExpr) String() string {
	return fmt.Sprintf("(%s%s)", e.Operator, e.Right.String())
}

// BinaryOp identifies a binary operator so evaluation can dispatch on an
// integer instead of repeatedly comparing the Operator string.
type BinaryOp uint8

// Binary operator kinds. BinaryOpUnknown covers any operator the classifier
// does not recognize, letting consumers fall back to the Operator string.
const (
	BinaryOpUnknown BinaryOp = iota
	BinaryOpAdd
	BinaryOpSub
	BinaryOpMul
	BinaryOpDiv
	BinaryOpMod
	BinaryOpLt
	BinaryOpLe
	BinaryOpGt
	BinaryOpGe
	BinaryOpEq
	BinaryOpNe
	BinaryOpAnd
	BinaryOpOr
)

// ClassifyBinaryOp maps an operator spelling to its BinaryOp, returning
// BinaryOpUnknown for anything unrecognized.
func ClassifyBinaryOp(op string) BinaryOp {
	switch op {
	case "+":
		return BinaryOpAdd
	case "-":
		return BinaryOpSub
	case "*":
		return BinaryOpMul
	case "/":
		return BinaryOpDiv
	case "%":
		return BinaryOpMod
	case "<":
		return BinaryOpLt
	case "<=":
		return BinaryOpLe
	case ">":
		return BinaryOpGt
	case ">=":
		return BinaryOpGe
	case "==":
		return BinaryOpEq
	case "!=":
		return BinaryOpNe
	case "and":
		return BinaryOpAnd
	case "or":
		return BinaryOpOr
	default:
		return BinaryOpUnknown
	}
}

// BinaryExpr represents an infix binary operator expression.
type BinaryExpr struct {
	Left         Expression
	Operator     string
	OperatorSpan Span
	Right        Expression
	// Op is the operator precomputed by ClassifyBinaryOp so evaluation can
	// dispatch on an integer. The parser sets it for every binary operator;
	// BinaryOpUnknown only arises for an unrecognized spelling, which the
	// evaluator rejects through the same path as any other invalid operator.
	Op BinaryOp
}

// expressionNode marks BinaryExpr as an expression node.
func (*BinaryExpr) expressionNode() {}

// String returns a compact debug representation of the binary expression.
func (e *BinaryExpr) String() string {
	return fmt.Sprintf("(%s %s %s)", e.Left.String(), e.Operator, e.Right.String())
}

// CallExpr represents a function call.
type CallExpr struct {
	Callee Expression
	Args   []Expression
}

// expressionNode marks CallExpr as an expression node.
func (*CallExpr) expressionNode() {}

// String returns a compact debug representation of the call.
func (e *CallExpr) String() string {
	args := make([]string, 0, len(e.Args))
	for _, arg := range e.Args {
		args = append(args, arg.String())
	}
	return fmt.Sprintf("%s(%s)", e.Callee.String(), strings.Join(args, ", "))
}

// TypeApplyExpr represents a call target with explicit static type arguments.
type TypeApplyExpr struct {
	Callee  Expression
	TypeArg string
}

// expressionNode marks TypeApplyExpr as an expression node.
func (*TypeApplyExpr) expressionNode() {}

// String returns a compact debug representation of the static type application.
func (e *TypeApplyExpr) String() string {
	return fmt.Sprintf("%s<%s>", e.Callee.String(), e.TypeArg)
}

// CastExpr represents an explicit cast<T>(value) conversion.
type CastExpr struct {
	TargetType  typ.Type
	Value       Expression
	KeywordSpan Span
}

// expressionNode marks CastExpr as an expression node.
func (*CastExpr) expressionNode() {}

// String returns a compact debug representation of the cast.
func (e *CastExpr) String() string {
	return fmt.Sprintf("cast<%s>(%s)", e.TargetType, e.Value.String())
}

// TryExpr unwraps a !T value or returns the error from the current function.
type TryExpr struct {
	Value Expression
}

// expressionNode marks TryExpr as an expression node.
func (*TryExpr) expressionNode() {}

// String returns a compact debug representation of the try expression.
func (e *TryExpr) String() string {
	return "try " + e.Value.String()
}

// UnsafeExpr marks an expression whose memory safety the compiler does not
// prove. It carries no value of its own: the marker says the author owns the
// obligation for every unproven operation inside Value.
type UnsafeExpr struct {
	Value Expression
	// Safety is the text of the `// SAFETY:` comment written above the
	// statement this marker sits in. The comment justifies the statement, so
	// every marker in one statement carries the same text.
	Safety string
	// Span points at the `unsafe` keyword, so a marker covering no such
	// operation can be reported where it was written.
	Span Span
}

// expressionNode marks UnsafeExpr as an expression node.
func (*UnsafeExpr) expressionNode() {}

// String returns a compact debug representation of the unsafe expression.
func (e *UnsafeExpr) String() string {
	return "unsafe " + e.Value.String()
}

// IndexExpr represents checked byte indexing or one-dimensional slicing.
type IndexExpr struct {
	Target Expression
	Index  Expression
	Start  Expression
	End    Expression
	Slice  bool
	// Span points at the `[`, so a bounds failure can name where it happened.
	Span Span
}

// expressionNode marks IndexExpr as an expression node.
func (*IndexExpr) expressionNode() {}

// String returns a compact debug representation of checked access.
func (e *IndexExpr) String() string {
	if !e.Slice {
		return fmt.Sprintf("%s[%s]", e.Target.String(), e.Index.String())
	}
	start := ""
	if e.Start != nil {
		start = e.Start.String()
	}
	end := ""
	if e.End != nil {
		end = e.End.String()
	}
	return fmt.Sprintf("%s[%s..%s]", e.Target.String(), start, end)
}

// StructLiteralExpr represents construction of a struct value.
type StructLiteralExpr struct {
	TypeName string
	Fields   []FieldValue
	// Span points at the type name, so a diagnostic about the construction as
	// a whole can be reported where the struct is named.
	Span Span
}

// expressionNode marks StructLiteralExpr as an expression node.
func (*StructLiteralExpr) expressionNode() {}

// String returns a compact debug representation of the struct literal.
func (e *StructLiteralExpr) String() string {
	fields := make([]string, 0, len(e.Fields))
	for _, field := range e.Fields {
		fields = append(fields, field.String())
	}
	return fmt.Sprintf("%s { %s }", e.TypeName, strings.Join(fields, ", "))
}

// FieldValue represents one field initializer in a struct literal.
type FieldValue struct {
	Name  string
	Value Expression
}

// String returns a compact debug representation of the field initializer.
func (v FieldValue) String() string {
	return fmt.Sprintf("%s: %s", v.Name, v.Value.String())
}

// FieldExpr represents field access on a receiver expression.
type FieldExpr struct {
	Receiver  Expression
	Name      string
	Namespace bool
	Span      Span
}

// expressionNode marks FieldExpr as an expression node.
func (*FieldExpr) expressionNode() {}

// String returns a compact debug representation of the field access.
func (e *FieldExpr) String() string {
	if e.Namespace {
		return e.Receiver.String() + "::" + e.Name
	}
	return e.Receiver.String() + "." + e.Name
}

// DerefExpr represents explicit postfix dereference with Zig-style .*
type DerefExpr struct {
	Receiver     Expression
	OperatorSpan Span
}

// expressionNode marks DerefExpr as an expression node.
func (*DerefExpr) expressionNode() {}

// String returns a compact debug representation of explicit dereference.
func (e *DerefExpr) String() string {
	return e.Receiver.String() + ".*"
}
