// Package selfhost generates the sources the Kizu compiler port needs but
// cannot read for itself. It exists only while the port does: cutover deletes
// the Go compiler and this package with it.
package selfhost

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/kizu-lang/kizu/internal/version"
)

// VersionSourcePath is where the generated version module lives, relative to
// the repository root. It is not checked in: the line names the revision, so
// it would change with every commit.
const VersionSourcePath = "compiler/src/internal/version/version_source.kizu"

// versionSourceTemplate is the generated module. The selfhost CLI has no
// linker flag to stamp and no build info to read, so the line the Go binary
// computes is written here as the constant it prints.
const versionSourceTemplate = "// Code generated by " +
	"`go run ./scripts/gen-selfhost-version`. DO NOT EDIT.\n" +
	"\n" +
	"/// Returns the line `kizu version` prints, the Go `version.String`\n" +
	"/// rendered from the same VCS state at the time this compiler was built.\n" +
	"pub fn version_string() -> []u8 {\n" +
	"    return %s;\n" +
	"}\n"

// WriteVersionSource writes the selfhost version module from the VCS state of
// the repository at root.
func WriteVersionSource(root string) error {
	revision, at, modified, err := repositoryVCS(root)
	if err != nil {
		return err
	}
	line := version.Format(version.Release, revision, at, modified)
	path := filepath.Join(root, filepath.FromSlash(VersionSourcePath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	source := fmt.Sprintf(versionSourceTemplate, kizuStringLiteral(line))
	// Written whole and moved into place: the test packages that build
	// `compiler/` each write this first and run beside one another, and a
	// reader must never see a file one of them is halfway through.
	staging, err := os.CreateTemp(filepath.Dir(path), "version_source.*.tmp")
	if err != nil {
		return err
	}
	if _, err := staging.Write([]byte(source)); err != nil {
		staging.Close()
		os.Remove(staging.Name())
		return err
	}
	if err := staging.Close(); err != nil {
		os.Remove(staging.Name())
		return err
	}
	if err := os.Chmod(staging.Name(), 0o644); err != nil {
		os.Remove(staging.Name())
		return err
	}
	return os.Rename(staging.Name(), path)
}

// repositoryVCS reads the revision, its time, and whether the tree carries
// uncommitted changes, the three values Go stamps into a binary it builds.
//
// Go stamps them only where it finds the repository: a `.git` directory. A
// linked worktree has a `.git` file instead, and `go build` there stamps
// nothing, so the Go binary names itself `kizu devel`. Reading git anyway
// would give the selfhost compiler a line the Go binary built from the same
// tree does not print.
func repositoryVCS(root string) (string, string, bool, error) {
	info, err := os.Stat(filepath.Join(root, ".git"))
	if errors.Is(err, os.ErrNotExist) {
		return "", "", false, nil
	}
	if err != nil {
		return "", "", false, err
	}
	if !info.IsDir() {
		return "", "", false, nil
	}
	revision, err := gitOutput(root, "rev-parse", "HEAD")
	if err != nil {
		return "", "", false, err
	}
	// Go records vcs.time as the commit time in UTC, so ask git for the same.
	at, err := gitOutput(root, "show", "-s", "--format=%cd",
		"--date=format-local:%Y-%m-%dT%H:%M:%SZ", "HEAD")
	if err != nil {
		return "", "", false, err
	}
	status, err := gitOutput(root, "status", "--porcelain")
	if err != nil {
		return "", "", false, err
	}
	return revision, at, status != "", nil
}

// gitOutput runs one git command in root and returns its trimmed output.
func gitOutput(root string, args ...string) (string, error) {
	command := exec.Command("git", args...)
	command.Dir = root
	// The commit time is asked for in local form, so pin the zone to UTC.
	command.Env = append(RepositoryEnv(), "TZ=UTC")
	out, err := command.Output()
	if err != nil {
		return "", fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
	}
	return strings.TrimSpace(string(out)), nil
}

// RepositoryEnv returns the environment with the variables that point git at
// a repository removed, so a git command reads the repository of the
// directory it runs in. A git hook runs with GIT_DIR set to the repository it was fired for,
// and that would otherwise win over the directory the command runs in.
func RepositoryEnv() []string {
	env := []string{}
	for _, entry := range os.Environ() {
		name, _, _ := strings.Cut(entry, "=")
		switch name {
		case "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE", "GIT_COMMON_DIR",
			"GIT_OBJECT_DIRECTORY", "GIT_PREFIX":
			continue
		}
		env = append(env, entry)
	}
	return env
}

// kizuStringLiteral renders one text as a Kizu single-line literal. Kizu reads
// the bytes between the quotes verbatim, so a text carrying a quote has no
// literal form; a version line cannot carry one.
func kizuStringLiteral(text string) string {
	if strings.ContainsAny(text, "\"\n") {
		return `""`
	}
	return `"` + text + `"`
}
