// Package selfhost generates the sources the Kizu compiler port needs but
// cannot read for itself. It exists only while the port does: cutover deletes
// the Go compiler and this package with it.
package selfhost

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/kizu-lang/kizu/internal/version"
)

// VersionSourcePath is where the generated version module lives, relative to
// the repository root. It is not checked in: the line names the revision, so
// it would change with every commit.
const VersionSourcePath = "compiler/src/internal/version/version_source.kizu"

// versionSourceTemplate is the generated module. The selfhost CLI has no
// linker flag to stamp and no build info to read, so the line the Go binary
// computes is written here as the constant it prints.
const versionSourceTemplate = "// Code generated by " +
	"`go run ./scripts/gen-selfhost-version`. DO NOT EDIT.\n" +
	"\n" +
	"/// Returns the line `kizu version` prints, the Go `version.String`\n" +
	"/// rendered from the same VCS state at the time this compiler was built.\n" +
	"pub fn version_string() -> []u8 {\n" +
	"    return %s;\n" +
	"}\n"

// WriteVersionSource writes the selfhost version module from the VCS state of
// the repository at root.
func WriteVersionSource(root string) error {
	revision, at, modified, err := repositoryVCS(root)
	if err != nil {
		return err
	}
	line := version.Format(version.Release, revision, at, modified)
	path := filepath.Join(root, filepath.FromSlash(VersionSourcePath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	source := fmt.Sprintf(versionSourceTemplate, kizuStringLiteral(line))
	return os.WriteFile(path, []byte(source), 0o644)
}

// repositoryVCS reads the revision, its time, and whether the tree carries
// uncommitted changes, the three values Go stamps into a binary it builds.
func repositoryVCS(root string) (string, string, bool, error) {
	revision, err := gitOutput(root, "rev-parse", "HEAD")
	if err != nil {
		return "", "", false, err
	}
	// Go records vcs.time as the commit time in UTC, so ask git for the same.
	at, err := gitOutput(root, "show", "-s", "--format=%cd",
		"--date=format-local:%Y-%m-%dT%H:%M:%SZ", "HEAD")
	if err != nil {
		return "", "", false, err
	}
	status, err := gitOutput(root, "status", "--porcelain")
	if err != nil {
		return "", "", false, err
	}
	return revision, at, status != "", nil
}

// gitOutput runs one git command in root and returns its trimmed output.
func gitOutput(root string, args ...string) (string, error) {
	command := exec.Command("git", args...)
	command.Dir = root
	// The commit time is asked for in local form, so pin the zone to UTC.
	command.Env = append(os.Environ(), "TZ=UTC")
	out, err := command.Output()
	if err != nil {
		return "", fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
	}
	return strings.TrimSpace(string(out)), nil
}

// kizuStringLiteral renders one text as a Kizu single-line literal. Kizu reads
// the bytes between the quotes verbatim, so a text carrying a quote has no
// literal form; a version line cannot carry one.
func kizuStringLiteral(text string) string {
	if strings.ContainsAny(text, "\"\n") {
		return `""`
	}
	return `"` + text + `"`
}
