[package]
name = "std"

[modules]
root = "std"
paths = ["src"]
exports = [
  "std::mem",
  "std::array",
  "std::string",
  "std::fmt",
  "std::testing",
  "std::kizu::ast",
  "std::kizu::lexer",
  "std::kizu::diagnostic",
  "std::kizu::parser",
  "std::fs",
  "std::path",
  "std::io",
  "std::process",
  "std::map",
  "std::task",
  "std::channel",
  "std::thread",
  "std::sync",
  "std::atomic",
]
